// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyRoWXOq6hTFgidu9_IwFy6bdlTTEHIw',
    appId: '1:839525348727:web:aa419d6ae3c5eae7419d72',
    messagingSenderId: '839525348727',
    projectId: 'tenadam-9ad66',
    authDomain: 'tenadam-9ad66.firebaseapp.com',
    storageBucket: 'tenadam-9ad66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWXyMc9C7Ioexx5hbYVqwq_oeiKKXVmo',
    appId: '1:839525348727:android:0def958fb65b9648419d72',
    messagingSenderId: '839525348727',
    projectId: 'tenadam-9ad66',
    storageBucket: 'tenadam-9ad66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCF1hsTdY8fiQbIt74pKHPyR-0iTjM3g',
    appId: '1:839525348727:ios:70b8962ed12aec00419d72',
    messagingSenderId: '839525348727',
    projectId: 'tenadam-9ad66',
    storageBucket: 'tenadam-9ad66.appspot.com',
    iosBundleId: 'com.example.tenadam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcCF1hsTdY8fiQbIt74pKHPyR-0iTjM3g',
    appId: '1:839525348727:ios:70b8962ed12aec00419d72',
    messagingSenderId: '839525348727',
    projectId: 'tenadam-9ad66',
    storageBucket: 'tenadam-9ad66.appspot.com',
    iosBundleId: 'com.example.tenadam',
  );
}
